### ISSUE TITLE
Problem with URL handling

### ISSUE THREAD

**Issue by lholdsworth** [jvanasco/metadata_parser#17]
The current logic for URL handling when its not provided in full seems to have an issue.

For example the website argos.co.uk uses a different domain for it's media, media.4rgos.it, and defines the OG image content value as _"//media.4rgos.it/the_image.jpg_".  The logic currently driving your URL handling in this instance changes that path to http://www.argos.co.uk/the_image.jpg.  So it seems it is not making any allowance for paths prefixed simply with "//" and instead is treating them exactly the same as if they were prefixed with just one "/".  Looks like it would be a quick fix?

**Comment by jvanasco** [comment]
can you provide a quick reproduction of this (e.g. at least an example url and the command which triggers this, unless you can do a 2-3 line script) and the version you're using?

on the current release, i'm just getting something like '//media.4rgos.it/the_image.jpg' UNLESS I'm grabbing a url via `get_metadata_link` (which triggers the logic to derive an absolute url).

**Comment by lholdsworth** [comment]
Ah no, my bad - you're right (I was using the _link version).  I'll close this.

**Comment by jvanasco** [comment]
Well there is a bug on the _link version.

I've got a fix in the works for og:image and image.  I'd just like to make sure I have the proper use cases for tests.

**Comment by jvanasco** [comment]
released in `0.9.21`
