### ISSUE TITLE
Feature Request: Pull image from html source if one does not exist in meta tags

### ISSUE THREAD

**Issue by cdrandin** [jvanasco/metadata_parser#24]
When a meta tag provides no info about an image src being used, then one will be picked from within the src.

The reasoning is at least a choice for an image to be displayed.

If there is a good spot where you think this implementation would be good at? I am not familiar with BeautifulSoup, but I'd be willing to try and tackle it.

**Comment by jvanasco** [comment]
This “feature” existed in an earlier version and was removed.  It is unlikely a good way to implement it within this library exists.

It is very easy to pull all the images out of the document with Beautiful Soup, but “all the images” includes all the image assets in the HTML used for design elements. This is often dozens of graphics.

To figure out the likely candidates for a representative image, you need a chunk of logic that can do something like:

* inspect the DOM to try and discern what the main content container is
* inspect all the images and try to figure out what logical options are, based on the URL or image dimensions 
* use Natural Language Processing or Machine Learning to analyze pages from the same domain, and discern what element is the likely page image 

There are at least a dozen other popular techniques.  I’ve used a handful of them by accessing the wrapped response in a post-processing follow-up routine, but a universal solution has never appeared.  The logic to get things right the most often, for us, has required building, training, and storing models.

**Comment by cdrandin** [comment]
Fair enough, I figured this would potentially be the case. Thanks for your response.
