### ISSUE TITLE
Other HTML parser library

### ISSUE THREAD

**Issue by javierfvargas** [jvanasco/metadata_parser#25]
In this line:
https://github.com/jvanasco/metadata_parser/blob/700cff4c0bc066a1fb0da52acaab15f6a244928d/metadata_parser/__init__.py#L1730

You force BeautifulSoup to use "html.parser", which in general is a good option, however sometimes one could prefer a more lenient parser as "html5lib", even knowing it is slower.

Would it be possible to let BeautifulSoup use the best available parser library? which means to call it without specifying a parser in that line.  Or maybe to add an option to use the default "html.parser" or the best available.

**Comment by jvanasco** [comment]
I’m open to supporting this, but i’m not sure how right now.  It would have to be an extra argument or something to override this behavior and maintain backwards compatibility.  I’ll think this over.

Thanks for this request.

**Comment by javierfvargas** [comment]
Well, I'm in kind of a rush so I forked your repo and did some changes while you officially support it.  I don't pretend you to use my code but if it is of any help, here is what i did.

https://github.com/javierfvargas/metadata_parser/commit/9a135a055ff8c28f189c818d319f7de70ddf899a

Thanks for your quick reply and for your nice library!

**Comment by jvanasco** [comment]
I'm leaning towards implementing this as method to override as a subclass

    def make_soup(self, html, **kwargs_bs):
        """
        Turns an HTML string into a BeautifulSoup document.
        If your project requires a specific parser, you can just override this here.
        """
        try:
            doc = BeautifulSoup(html, "lxml", **kwargs_bs)
        except:
            doc = BeautifulSoup(html, "html.parser", **kwargs_bs)
        return doc

For your usage then...

	class MyParser(MetadataParser):
		def make_soup(self, html, **kwargs_bs):
			doc = BeautifulSoup(html, **kwargs_bs)
			return doc

**Comment by jvanasco** [comment]
I've got the subclass version in master now, via this commit https://github.com/jvanasco/metadata_parser/commit/e5982cb202806562bfb5be9a8cd1481f6fbdbd69

**Comment by javierfvargas** [comment]
Thank you so much.  Will pull it from master then. Will keep you posted!

**Comment by jvanasco** [comment]
Just for context of why I decided on a method To override:

- there are too many kwargs already. My bad!
- this gives more control to developers
- at least one other function was split out to a method for developers to override

Thanks for bringing up this request. I’m sure many people will benefit from it.

**Comment by javierfvargas** [comment]
I agree, the subclassing strategy is way better than adding another argument.  

And yes, adding this capability helps a lot you can choose exactly what you want.  In my case by allowing the html5lib parser I get slower but better results in all cases, which is what I prefer for my use case.  With this trick, for some special URLs, your lib outperforms some pages out there doing the same job.

**Comment by jvanasco** [comment]
This is on pypi as 0.10.3; sorry for the delay. i forgot to tag & release a few months ago.
