### ISSUE TITLE
warns on python3

### ISSUE THREAD

**Issue by NightMachinary** [jvanasco/metadata_parser#26]
```
/Users/evar/anaconda/lib/python3.7/site-packages/metadata_parser/__init__.py:1247: FutureWarning: `search_head_only` was not provided and defaulting to `True` Future versions will default to `False`.
  warn_future("""`search_head_only` was not provided and defaulting to `True` """
```

**Comment by jvanasco** [comment]
This is intentional and happens on Python2 and Python3. Release `0.8.0` introduced the new kwarg `search_head_only`. It currently defaults to `True` for backwards compatibility but will default to the more correct `False` in the future.
