### ISSUE TITLE
Error when parsing URL NotParsableFetchError: Status Code is not 200 | 429 | None

### ISSUE THREAD

**Issue by ledzgio** [jvanasco/metadata_parser#28]
I am trying to parse a twitter URL and it works on my local installation, while it doesn't work (with the same code) in the deployment server. I get this error:

`
>>> metadata_parser.MetadataParser(url="https://twitter.com/elonmusk/status/1278756565160468481", search_head_only=False, support_malformed=True, force_doctype=True, url_headers={'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36'})
`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/poc_platform/env3.7/lib/python3.7/site-packages/metadata_parser/__init__.py", line 1273, in __init__
    retry_dropped_without_headers=retry_dropped_without_headers,
  File "/home/admin/poc_platform/env3.7/lib/python3.7/site-packages/metadata_parser/__init__.py", line 1469, in fetch_url
    metadataParser=self,
metadata_parser.NotParsableFetchError: NotParsableFetchError: Status Code is not 200 | 429 | None

any idea?

**Comment by jvanasco** [comment]
200 is the expected HTTP status code. 

You received a 429 as the status code -- too many requests.

Your ip was ratelimited.
