### ISSUE TITLE
[Feature] Cache soup (and other) objects by sha256sum

### ISSUE THREAD

**Issue by mzpqnxow** [jvanasco/metadata_parser#31]
When running against a very large corpus there is an opportunity for a non-negligible performance gain from caching the full operations of `MetadataParser` using a sum over the HTML content, at least when across over 100k-200k+ pages that contain a high percentage of duplicates which is the case for my use

This is something I'm planning on implementing anyway because in my case, my corpus already has the `sha256_sum` available before sending it to `MetadataParser`. The only question is whether I do it on the front-end on my side of the project, or contribute it as a PR to your project

If I implement it for `MetadataParser`, I'll be doing it such that the sha256sum can be sent precalculated via a constructor `kwargs` value along with `html=`

If you do not want this as a feature or have any comments about possible problems that might crop up, it would be great if you could post a comment in the next day or two so I can make an educated decision on where to place this

I'm expecting it to be a simple CPU/RAM tradeoff, which I can afford in my case

The only constraint/requirement for me is that sha256 must be used as the algorithm- though it wouldn't be much work for me to add multiple algorithms as optional

Thanks!

**Comment by jvanasco** [comment]
Thanks for offering this. I somehow never saw this until it was just closed.

**Comment by mzpqnxow** [comment]
> Thanks for offering this. I somehow never saw this until it was just closed.
> 
> 

And I just saw your response, a little late. So now we're even 😃
