### ISSUE TITLE
Not supporting python3

### ISSUE THREAD

**Issue by nahuelange** [jvanasco/metadata_parser#5]
Hi,
This module doesn't support python3, isn't it ?

**Comment by jvanasco** [comment]
It was patched about 2 years ago to support python 3 and probably still does, but is only officially tested/supported on python 2.7.x

**Comment by MindMapMaker** [comment]
The following patch in __init__.py line 9ish will fix it to work with Python 3x. 

try:
    import urlparse
except:
    from urllib.parse import urlparse

Thanks for a great little package! Very handy.
