### ISSUE TITLE
get_field function? in MetadaParser

### ISSUE THREAD

**Issue by WeaverStever** [jvanasco/metadata_parser#6]
From the example, **From an URL** "print page.metadata" works as expected.  However, "print page.get_field('title')" returns an error:  

AttributeError: 'MetadataParser' object has no attribute 'get_field'

Python 2.7.6
Successful imports on metadata_parser, lxml, BeautifulSoup

**Comment by jvanasco** [comment]
Thanks for catching this.  `get_field` was renamed into `get_metadata` a while back.

Looking at my notes, it seems that this happened before the public 0.4.1 release.

I fixed the docs in the `0.6.15` release

**Comment by WeaverStever** [comment]
Thanks for your quick response, keeps my project moving..

print page.get_metadata('title') works as expected.

If the field queried is not in the document, the result is "None" -- also
as expected.

I'm a bit of a newbie to Python. It appears that the processing occurs in
__init__.py.  I'm planning a CGI web implementation, what would need to be
done to include in a common cgi-bin directory?

Thanks again,

Steve Kritzer
